# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ridamsinha20@gmailcom
author_name: RIDAMSINHA
contract_name: green_gauge
deployment_language: python
preset_name: starter
project_name: GreenGauge

